logging:
  level:
    root: INFO
    io.github.jotabrc.ovy_mq: TRACE
  pattern:
    console: "%date [%thread] [%-5level] %logger{40} - %message%n"

# Global values
ovymq.client.processing.timeout: 150000

ovymq.task.session-destroy.initial-delay: 10000
ovymq.task.session-destroy.fixed-delay: 35000

ovymq.task.listener-poll.initial-delay: 10000
ovymq.task.listener-poll.fixed-delay: 35000

ovymq.task.health-check.initial.delay: 10000
ovymq.task.health-check.fixed-delay: 60000
ovymq.task.health-check.expiration-time: 120000

ovymq.session-manager.connection.max-retries: 50
ovymq.session-manager.connection.timeout: 150000

ovymq.config-client.timeout: 150000
ovymq.config-client.initial-delay: 10000
ovymq.config-client.fixed-delay: 35000


spring:
  application.name: OVY_Mq_client
  config:
    import: classpath:credential.yml
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
