logging:
  level:
    root: INFO
    io.github.jotabrc.ovy_mq: TRACE
  pattern:
    console: "%date [%thread] [%-5level] %logger{40} - %message%n"

ovymq:
  task:
    consumer:
      active: true
      delay: 10000
    health-check:
      active: true
      delay: 60000
      threshold: 65000
  session:
    connection:
      timeout: 1000
      backoff: 10


spring:
  application.name: OVY_Mq_client
  config:
    import: classpath:credential.yml
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
