server:
  port: 9090
spring:
  profiles:
    active: dev
  application.name: OVY_Mq
  config:
    import: classpath:credential.yml

ovymq:
  task:
    reaper:
      active: true
      delay: 60000

logging:
  level:
    root: INFO
    io.github.jotabrc.ovy_mq: TRACE
  pattern:
    console: "%date [%thread] [%-5level] %logger{40} - %message%n"

ovymq.task.shutdown.wait-delay: 1000
ovymq.task.shutdown.max-wait: 180000